# Site settings
title: flyer's blog
email: flyer103@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flyer103.github.io" # the base hostname & protocol for your site
twitter_username: flyer103
github_username:  flyer103

# Build settings
markdown: kramdown

timezone: Asia/Shanghai
encoding: utf-8
author: flyer
author_email: flyer103@gmail.com
permalink: pretty
paginate: 10
