# Site settings
title: flyer's blog
email: flyer103@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: flyer103
github_username:  flyer103

# Build settings
markdown: kramdown
